config/routes.rb
# -*- encoding : utf-8 -*-
CUALimpieza::Application.routes.draw do

  get 'errors/not_found'
  get 'errors/server_error'
  get 'logs/show_since'

  namespace :limpieza do
    get 'general/index', :as => 'general'

    get 'agenda' => 'agenda#index', :as =>'agenda'
    get 'agenda/index' => 'agenda#index'
    get 'agenda/load_zone' => 'agenda#load_zone'
    #get_cleanup_request está hardcodeada en agenda.js.erb
    get 'agenda/get_cleanup_requests' => 'agenda#get_cleanup_request', :as => 'agenda_cleanup_request'
    get 'agenda/print_cleanup_requests', :as => 'print_cleanup_requests'
    get 'agenda/print_cleanup_requests_post', :as => 'print_cleanup_requests_post'
    get 'agenda/print_cleanup_requests_page', :as => 'print_cleanup_requests_page'

    post 'agenda/importar_excel' => 'agenda#import_excel', :as =>'import_excel'

    get 'calendario/index', :as =>'calendario'
    get 'calendario/get_events'
    # terminal cleanup
    get 'calendario/new', :as => 'new_terminal_cleanup'
    post 'calendario/create', :as => 'create_terminal_cleanup'
    get 'calendario/edit', :as => 'edit_terminal_cleanup'
    put 'calendario/update', :as => 'update_terminal_cleanup'
    delete 'calendario/destroy', :as => 'delete_terminal_cleanup'
    # terminal cleanup instance
    get 'calendario/new_tc_instance', :as => 'new_tc_instance'
    post 'calendario/create_tc_instance', :as => 'create_tc_instance'
    get 'calendario/edit_tc_instance', :as => 'edit_tc_instance'
    put 'calendario/update_tc_instance', :as => 'update_tc_instance'

    # Rooms view
    get 'vista_salas' => 'roomsView#index', :as =>'vista_salas'
    get 'vista_salas/index' => 'roomsView#index'

    get 'vista_salas/edit_room_status' => 'roomsView#edit_room_status' , :as => 'edit_room_status'
    put 'vista_salas/change_room_status' => 'roomsView#change_room_status' , :as => 'change_room_status'
    get 'vista_salas/edit_maintenance_room' => 'roomsView#edit_maintenance_room', :as => 'edit_maintenance_room'
    put 'vista_salas/finish_maintenance' => 'roomsView#finish_maintenance', :as => 'finish_maintenance'

    # Read-Only Rooms view
    get 'vista_salas/ver' => 'roomsView#show', :as => 'show_rooms_readonly'

    #Popups Cleanup Requests
    get 'popup_nueva_solicitud' => 'cleanup_popup#popup_cleanup_request_new', :as => 'new_cleanup_request'
    post 'crear_solicitud' => 'cleanup_popup#create', :as =>'create_cleanup_request'

    get 'popup_solicitud/:id' => 'cleanup_popup#popup_cleanup_request_show', :as => 'show_cleanup_request'
    post 'eliminar_solicitud' => 'cleanup_popup#delete', :as => 'delete_cleanup_request'
    put 'procesar_solicitud' => 'cleanup_popup#process_cleanup_request', :as => 'process_cleanup_request'
  end

  namespace :api do
    get 'rooms/sector/:id' => 'rooms#rooms_by_sector', :as => 'rooms_by_sector'
    get 'rooms/load_zone' => 'rooms#load_zone'
    get 'rooms/load_sector' => 'rooms#load_sector'
    resources :rooms
    get 'logs/show' => 'logs#show'
    get 'employees/:id' => 'employees#show'
    get 'employees/:id/vacations' => 'employees#employee_vacations'
  end

  namespace :personal do
    # Employees_Controller:
    get 'index' => 'employees#list', :as => 'employees_list'
    get 'nuevo_empleado' => 'employees#new', :as => 'new_employee'
    post 'crear_empleado' => 'employees#create', :as => 'create_employee'
    get 'editar_empleado/:id' => 'employees#edit', :as => 'edit_employee'
    put 'actualizar_empleado/:id' => 'employees#update', :as => 'update_employee'

    get 'historial_trabajo/:id' => 'employees#work_history', :as => 'work_history'
    get 'historial_limpieza/:id' => 'employees#cleaning_history', :as => 'cleaning_history'
    get 'asignar_turno/:id' => 'employees#assign_shift', :as => 'assign_shift'
    get 'get_shifts' => 'employees#get_shifts', :as => 'get_shifts'
    put 'update_shifts/:id' => 'employees#update_shifts', :as => 'update_shifts'

    #Shifts_Controller:
    get 'turnos' => 'shifts#index', :as => 'shifts'
    get 'turnos/nuevo_turno' => 'shifts#get_new_shift', :as => 'get_new_shift'
    get 'turnos/ver_turno' => 'shifts#get_shift', :as => 'get_shift'
    post 'turnos/crear_turno' => 'shifts#create', :as => 'create_shift'
    get 'shifts/shift_form', :as => 'shift_form'
    put 'turnos/actualizar/:id' => 'shifts#update', :as => 'update_shift'

    #Assistances_Controller:
    get 'asistencias' => 'assistances#index', :as => 'assistances'
    post 'asistencia_update' => 'assistances#update', :as => 'update'

    #Vacations controller:
    get 'vacaciones' => 'vacations#index', :as => 'vacations'
    get 'vacaciones/get_events' => 'vacations#get_events'
    get 'vacaciones/new' => 'vacations#new', :as => 'new_vacation'
    post 'vacaciones/create' => 'vacations#create', :as => 'create_vacation'
    get 'vacaciones/edit/:id' => 'vacations#edit', :as => 'edit_vacation'
    put 'vacaciones/edit/:id' => 'vacations#update', :as => 'update_vacation'
  end

  namespace :administracion do
    #--------------------------usuarios------------------------------
    get 'index' => 'users#list', :as => 'users_list'
    get 'usuarios/nuevo' => 'users#new', :as => 'new_user'
    post 'usuarios/crear' => 'users#create', :as => 'create_user'
    get 'usuarios/editar/:id' => 'users#edit', :as => 'edit_user'
    put 'usuarios/actualizar/:id' => 'users#update', :as => 'update_user'
    get 'usuarios/cambio_contrasena/:id' => 'users#password_change', :as =>'password_change'
    put 'usuarios/actualizar_contrasena/:id' => 'users#password_update', :as =>'password_update'

    #--------------------------salas------------------------------
    get 'salas/lista' => 'rooms#list', :as => 'rooms_list'
    get 'salas/nuevo' => 'rooms#new', :as => 'new_room'
    post 'salas/crear' => 'rooms#create', :as => 'create_room'
    get 'salas/editar/:id' => 'rooms#edit', :as => 'edit_room'
    put 'salas/actualizar/:id' => 'rooms#update', :as => 'update_room'

    #--------------------------sectores------------------------------
    get 'sectores/lista' => 'sectors#list', :as => 'sectors_list'
    get 'sectores/nuevo' => 'sectors#new', :as => 'new_sector'
    post 'sectores/crear' => 'sectors#create', :as => 'create_sector'
    get 'sectores/editar/:id' => 'sectors#edit', :as => 'edit_sector'
    put 'sectores/actualizar/:id' => 'sectors#update', :as => 'update_sector'

    #--------------------------solicitudes de limpieza------------------------------
    get 'solicitudes_limpieza/lista' => 'cleanup_requests#list', :as => 'cleanup_requests_list'
    get 'solicitudes_limpieza/ver/:id' => 'cleanup_requests#show', :as => 'cleanup_request_show'

  end

  get 'cambiar_contrasena' => 'home#my_password_change', :as =>'my_password_change'
  put 'actualizar_mi_contrasena' => 'home#my_password_update', :as =>'my_password_update'

  post 'home/login'  => 'home#login', :as => 'login'
  get 'home/logout'  => 'home#logout', :as => 'logout'

  #Paginas de error:
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'home#index'
end

app/views/shared/_administration_sidebar.html.erb
<div class='sidebar-nav well'>
  <ul class='nav nav-pills nav-stacked'>
    <li class='nav-header'>Módulo Administración</li>
    <li class='<%= 'active' if @current_controller == 'users' %>'>
      <%= link_to administracion_users_list_path do %>
          <i class='icon-user icon-<% if @current_controller == 'users' %>white<% else %>black<% end %>'></i>
          Usuarios
      <% end %>
    </li>
    <li class='<%= 'active' if @current_controller == 'sectors' %>'>
      <%= link_to administracion_sectors_list_path do %>
          <i class='icon-th-large icon-<% if @current_controller == 'sectors' %>white<% else %>black<% end %>'></i>
          Sectores
      <% end %>
    </li>
    <li class='<%= 'active' if @current_controller == 'rooms' %>'>
      <%= link_to administracion_rooms_list_path do %>
          <i class='icon-th icon-<% if @current_controller == 'rooms' %>white<% else %>black<% end %>'></i>
          Salas
      <% end %>
    </li>
    <li class='<%= 'active' if @current_controller == 'cleanup_requests' %>'>
      <%= link_to administracion_cleanup_requests_list_path do %>
          <i class='icon-file icon-<% if @current_controller == 'cleanup_requests' %>white<% else %>black<% end %>'></i>
          Solicitudes de Limpieza Cerradas
      <% end %>
    </li>
  </ul>
</div><!--/.well -->

app/views/shared/_cleanup_sidebar.erb
<div class="sidebar-nav well">
  <!-- TODO: Hacer el menu no estatico (https://github.com/seyhunak/twitter-bootstrap-rails) -->
  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">Módulo Limpieza</li>
    <li class="<%= "active" if @current_controller == "general" %>">
      <%= link_to :controller => 'limpieza/general' do %>
          <i class="icon-home icon-<% if @current_controller == "general" %>white<% else %>black<% end %>"></i>
          General
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "agenda" %>">
      <%= link_to :controller => 'limpieza/agenda' do %>
          <i class="icon-book icon-<% if @current_controller == "agenda" %>white<% else %>black<% end %>"></i>
          Agenda diaria
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "calendario" %>">
      <%= link_to :controller => 'limpieza/calendario' do %>
          <i class="icon-calendar icon-<% if @current_controller == "calendario" %>white<% else %>black<% end %>"></i>
          Calendario
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "rooms_view" %>">
      <%= link_to :controller => 'limpieza/roomsView' do %>
          <i class="icon-th-large icon-<% if @current_controller == "rooms_view" %>white<% else %>black<% end %>"></i>
          Vista de Salas
      <% end %>
    </li>
  </ul>
</div><!--/.well -->

app/views/shared/_cleanup_sidebar.html.erb
<div class="sidebar-nav well">
  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">Módulo Limpieza</li>
    <li class="<%= "active" if @current_controller == "general" %>">
      <%= link_to limpieza_general_path do %>
          <i class="icon-home icon-<% if @current_controller == "general" %>white<% else %>black<% end %>"></i>
          General
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "agenda" %>">
      <%= link_to limpieza_agenda_path do %>
          <i class="icon-book icon-<% if @current_controller == "agenda" %>white<% else %>black<% end %>"></i>
          Agenda diaria
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "calendario" %>">
      <%= link_to limpieza_calendario_path do %>
          <i class="icon-calendar icon-<% if @current_controller == "calendario" %>white<% else %>black<% end %>"></i>
          Calendario
      <% end %>
    </li>
    <li class="<%= "active" if @current_controller == "rooms_view" %>">
      <%= link_to limpieza_vista_salas_path do %>
          <i class="icon-th-large icon-<% if @current_controller == "rooms_view" %>white<% else %>black<% end %>"></i>
          Vista de Salas
      <% end %>
    </li>
  </ul>
</div><!--/.well -->

app/views/shared/_legend_priority.html.erb
<div class='legend-priority'>
    <strong>Prioridad</strong>: <span class="legend-square priority-1"></span> Alta
               <span class="legend-square priority-2"></span> Media
               <span class="legend-square priority-3"></span> Baja
</div>

app/views/shared/_legend_room_status.html.erb
<div class='legend-room-status'>
  <div class = 'row-fluid'>
    <div class='span4'>
      <span class="legend-square status-free"></span> Libre (<%=Room.count_for_status('free')%>)
    </div>
    <div class='span4'>
      <span class="legend-square status-occupied"></span> Ocupada (<%=Room.count_for_status('occupied')%>)
    </div>
    <div class='span4'>
      <span class="legend-square status-maintenance"></span> En Mantenimiento (<%=Room.count_for_status('maintenance')%>)
    </div>
  </div>
  <div class='row-fluid'>
    <div class='span4'>
      <span class="legend-square status-pending"></span> Solicitud pendiente  (<%=Room.count_for_status('pending')%>)
    </div>
    <div class='span4'>
      <span class="legend-square status-cleaning"></span> En Limpieza (<%=Room.count_for_status('cleaning')%>)
    </div>
  </div>
</div>

app/views/shared/_modal_popup.html.erb
<div id="modal-popup" class="modal hide" tabindex="-1" role="dialog">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <div id="modal-content">
    <%= image_tag 'cargando.gif', :class => 'loading-img' %>
  </div>
</div>

app/views/shared/_model_errors.html.erb
<% if token.errors.any? %>
    <div id="error_explanation" class='alert alert-error'>
      <ul>
        <% token.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_personal_sidebar.html.erb
<div class="sidebar-nav well">
  <ul class="nav nav-pills nav-stacked">
    <li class="nav-header">Módulo Personal</li>
    <% unless @current_user.coordinator? %>
        <li class="<%= "active" if @current_controller == "employees" %>">
          <%= link_to personal_employees_list_path do %>
              <i class="icon-user icon-<% if @current_controller == "employees" %>white<% else %>black<% end %>"></i>
              Empleados
          <% end %>
        </li>
        <li class="<%= "active" if @current_controller == "shifts" %>">
          <%= link_to personal_shifts_path do %>
              <i class="icon-briefcase icon-<% if @current_controller == "shifts" %>white<% else %>black<% end %>"></i>
              Turnos
          <% end %>
        </li>
    <%end%>
    <li class="<%= "active" if @current_controller == "assistances" %>">
      <%= link_to personal_assistances_path do %>
          <i class="icon-list-alt icon-<% if @current_controller == "assistances" %>white<% else %>black<% end %>"></i>
          Asistencia
      <% end %>
    </li>
    <%unless @current_user.coordinator? %>
        <li class="<%= "active" if @current_controller == "vacations" %>">
          <%= link_to personal_vacations_path do %>
              <i class="icon-star icon-<% if @current_controller == "vacations" %>white<% else %>black<% end %>"></i>
              Vacaciones y Permisos
          <% end %>
        </li>
    <%end%>
  </ul>
</div><!--/.well -->

app/views/shared/_search_form.html.erb
<%= form_tag action_url, :method => 'get', :id => 'rooms-search' do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], :class=>'input-large'  %>
      <%= submit_tag search_label, :class=>'btn' %>
    </div>
<% end %>

app/views/shared/_session_nav_bar.html.erb
<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to 'Aseo y Limpieza', root_path ,:class=>'brand visible-desktop' %>
      <!-- TODO: Hacer el menu no estatico (https://github.com/seyhunak/twitter-bootstrap-rails) -->
      <% unless @current_user.read_only? %>
          <ul class="nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-asterisk"></i>
                <span id="realtime-notification-counter" class="badge badge-success"></span>
                <b class="caret"></b>
              </a>
              <ul id="realtime-notification-container" class="dropdown-menu">
                <li id="dummy-notification" class="disabled"><a><i class="icon-ok-sign"></i> No hay actividad reciente.</a></li>
              </ul>
            </li>
            <li class="divider-vertical"></li>
            <% class_type = (@current_module == 'limpieza') ? 'active' : 'inactive' %>
            <li class="<%= class_type %>"><%= link_to 'Limpieza', limpieza_general_path  %></li>
            <% class_type = (@current_module == 'personal') ? 'active' : 'inactive' %>
            <li class="<%= class_type %>"><%= link_to 'Personal', personal_employees_list_path  %></li>
            <% if @current_user.admin? %>
                <% class_type = (@current_module == 'administracion') ? 'active' : 'inactive' %>
                <li class="<%= class_type %>"><%= link_to 'Administración', administracion_users_list_path %></li>
            <% end %>
          </ul>
      <%end%>

      <ul class="nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-user"></i>
            <strong><%=@current_user.short_name%></strong>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cambiar contraseña', my_password_change_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Cerrar sesión', logout_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/modal_popup_redirect.html.erb
REDIRECT:<%= @redirect.html_safe %>

app/views/shared/modal_popup_success.html.erb
OK