config/routes.rb
# -*- encoding : utf-8 -*-
CUALimpieza::Application.routes.draw do

  get 'errors/not_found'
  get 'errors/server_error'
  get 'logs/show_since'

  namespace :limpieza do
    get 'general/index', :as => 'general'

    get 'agenda' => 'agenda#index', :as =>'agenda'
    get 'agenda/index' => 'agenda#index'
    get 'agenda/load_zone' => 'agenda#load_zone'
    #get_cleanup_request está hardcodeada en agenda.js.erb
    get 'agenda/get_cleanup_requests' => 'agenda#get_cleanup_request', :as => 'agenda_cleanup_request'
    get 'agenda/print_cleanup_requests', :as => 'print_cleanup_requests'
    get 'agenda/print_cleanup_requests_post', :as => 'print_cleanup_requests_post'
    get 'agenda/print_cleanup_requests_page', :as => 'print_cleanup_requests_page'

    post 'agenda/importar_excel' => 'agenda#import_excel', :as =>'import_excel'

    get 'calendario/index', :as =>'calendario'
    get 'calendario/get_events'
    # terminal cleanup
    get 'calendario/new', :as => 'new_terminal_cleanup'
    post 'calendario/create', :as => 'create_terminal_cleanup'
    get 'calendario/edit', :as => 'edit_terminal_cleanup'
    put 'calendario/update', :as => 'update_terminal_cleanup'
    delete 'calendario/destroy', :as => 'delete_terminal_cleanup'
    # terminal cleanup instance
    get 'calendario/new_tc_instance', :as => 'new_tc_instance'
    post 'calendario/create_tc_instance', :as => 'create_tc_instance'
    get 'calendario/edit_tc_instance', :as => 'edit_tc_instance'
    put 'calendario/update_tc_instance', :as => 'update_tc_instance'

    # Rooms view
    get 'vista_salas' => 'roomsView#index', :as =>'vista_salas'
    get 'vista_salas/index' => 'roomsView#index'

    get 'vista_salas/edit_room_status' => 'roomsView#edit_room_status' , :as => 'edit_room_status'
    put 'vista_salas/change_room_status' => 'roomsView#change_room_status' , :as => 'change_room_status'
    get 'vista_salas/edit_maintenance_room' => 'roomsView#edit_maintenance_room', :as => 'edit_maintenance_room'
    put 'vista_salas/finish_maintenance' => 'roomsView#finish_maintenance', :as => 'finish_maintenance'

    # Read-Only Rooms view
    get 'vista_salas/ver' => 'roomsView#show', :as => 'show_rooms_readonly'

    #Popups Cleanup Requests
    get 'popup_nueva_solicitud' => 'cleanup_popup#popup_cleanup_request_new', :as => 'new_cleanup_request'
    post 'crear_solicitud' => 'cleanup_popup#create', :as =>'create_cleanup_request'

    get 'popup_solicitud/:id' => 'cleanup_popup#popup_cleanup_request_show', :as => 'show_cleanup_request'
    post 'eliminar_solicitud' => 'cleanup_popup#delete', :as => 'delete_cleanup_request'
    put 'procesar_solicitud' => 'cleanup_popup#process_cleanup_request', :as => 'process_cleanup_request'
  end

  namespace :api do
    get 'rooms/sector/:id' => 'rooms#rooms_by_sector', :as => 'rooms_by_sector'
    get 'rooms/load_zone' => 'rooms#load_zone'
    get 'rooms/load_sector' => 'rooms#load_sector'
    resources :rooms
    get 'logs/show' => 'logs#show'
    get 'employees/:id' => 'employees#show'
    get 'employees/:id/vacations' => 'employees#employee_vacations'
  end

  namespace :personal do
    # Employees_Controller:
    get 'index' => 'employees#list', :as => 'employees_list'
    get 'nuevo_empleado' => 'employees#new', :as => 'new_employee'
    post 'crear_empleado' => 'employees#create', :as => 'create_employee'
    get 'editar_empleado/:id' => 'employees#edit', :as => 'edit_employee'
    put 'actualizar_empleado/:id' => 'employees#update', :as => 'update_employee'

    get 'historial_trabajo/:id' => 'employees#work_history', :as => 'work_history'
    get 'historial_limpieza/:id' => 'employees#cleaning_history', :as => 'cleaning_history'
    get 'asignar_turno/:id' => 'employees#assign_shift', :as => 'assign_shift'
    get 'get_shifts' => 'employees#get_shifts', :as => 'get_shifts'
    put 'update_shifts/:id' => 'employees#update_shifts', :as => 'update_shifts'

    #Shifts_Controller:
    get 'turnos' => 'shifts#index', :as => 'shifts'
    get 'turnos/nuevo_turno' => 'shifts#get_new_shift', :as => 'get_new_shift'
    get 'turnos/ver_turno' => 'shifts#get_shift', :as => 'get_shift'
    post 'turnos/crear_turno' => 'shifts#create', :as => 'create_shift'
    get 'shifts/shift_form', :as => 'shift_form'
    put 'turnos/actualizar/:id' => 'shifts#update', :as => 'update_shift'

    #Assistances_Controller:
    get 'asistencias' => 'assistances#index', :as => 'assistances'
    post 'asistencia_update' => 'assistances#update', :as => 'update'

    #Vacations controller:
    get 'vacaciones' => 'vacations#index', :as => 'vacations'
    get 'vacaciones/get_events' => 'vacations#get_events'
    get 'vacaciones/new' => 'vacations#new', :as => 'new_vacation'
    post 'vacaciones/create' => 'vacations#create', :as => 'create_vacation'
    get 'vacaciones/edit/:id' => 'vacations#edit', :as => 'edit_vacation'
    put 'vacaciones/edit/:id' => 'vacations#update', :as => 'update_vacation'
  end

  namespace :administracion do
    #--------------------------usuarios------------------------------
    get 'index' => 'users#list', :as => 'users_list'
    get 'usuarios/nuevo' => 'users#new', :as => 'new_user'
    post 'usuarios/crear' => 'users#create', :as => 'create_user'
    get 'usuarios/editar/:id' => 'users#edit', :as => 'edit_user'
    put 'usuarios/actualizar/:id' => 'users#update', :as => 'update_user'
    get 'usuarios/cambio_contrasena/:id' => 'users#password_change', :as =>'password_change'
    put 'usuarios/actualizar_contrasena/:id' => 'users#password_update', :as =>'password_update'

    #--------------------------salas------------------------------
    get 'salas/lista' => 'rooms#list', :as => 'rooms_list'
    get 'salas/nuevo' => 'rooms#new', :as => 'new_room'
    post 'salas/crear' => 'rooms#create', :as => 'create_room'
    get 'salas/editar/:id' => 'rooms#edit', :as => 'edit_room'
    put 'salas/actualizar/:id' => 'rooms#update', :as => 'update_room'

    #--------------------------sectores------------------------------
    get 'sectores/lista' => 'sectors#list', :as => 'sectors_list'
    get 'sectores/nuevo' => 'sectors#new', :as => 'new_sector'
    post 'sectores/crear' => 'sectors#create', :as => 'create_sector'
    get 'sectores/editar/:id' => 'sectors#edit', :as => 'edit_sector'
    put 'sectores/actualizar/:id' => 'sectors#update', :as => 'update_sector'

    #--------------------------solicitudes de limpieza------------------------------
    get 'solicitudes_limpieza/lista' => 'cleanup_requests#list', :as => 'cleanup_requests_list'
    get 'solicitudes_limpieza/ver/:id' => 'cleanup_requests#show', :as => 'cleanup_request_show'

  end

  get 'cambiar_contrasena' => 'home#my_password_change', :as =>'my_password_change'
  put 'actualizar_mi_contrasena' => 'home#my_password_update', :as =>'my_password_update'

  post 'home/login'  => 'home#login', :as => 'login'
  get 'home/logout'  => 'home#logout', :as => 'logout'

  #Paginas de error:
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'home#index'
end

app/controllers/administracion/administration_controller.rb
# -*- encoding : utf-8 -*-
class Administracion::AdministrationController < ApplicationController
  def list
    @users = User.paginate(:page => params[:page], :per_page => 10)
    render 'index'
  end

  def new
    @user = User.new
    @is_new = true
    render 'user'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = 'Usuario creado exitosamente'
      redirect_to :administracion_users_list
    else
      @is_new = true
      render 'user'
    end
  end

  def edit
    @user = User.find(params[:id])
    @is_new = false
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
    render 'user'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_users_list
    else
      @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
        flash.now[:notice] = 'Usuario actualizado exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar al usuario'
      end
      @is_new = false
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'user'
    end
  end

  def password_change
    @user = User.find(params[:id])
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
  end

  def password_update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_users_list
    else
      @user = User.find(params[:id])
      pass = params[:user][:password]
      pass_conf = params[:user][:password_confirmation]
      if @user.update_attributes(password: pass , password_confirmation: pass_conf)
        flash.now[:notice] = 'Contraseña de usuario actualizada exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar la contraseña del usuario'
      end
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'password_change'
    end
  end
end

app/controllers/administracion/cleanup_requests_controller.rb
class Administracion::CleanupRequestsController < ApplicationController
  def list
    @cleanup_requests = CleanupRequest.get_closed.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @cleanup_request = CleanupRequest.find(params[:id])
  end
end

app/controllers/administracion/rooms_controller.rb
# -*- encoding : utf-8 -*-
class Administracion::RoomsController < ApplicationController
  def list
    @rooms = Room.get_list_with_search(params[:search]).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @room = Room.new
    @is_new = true
    render 'room'
  end

  def create
    @room = Room.new(params[:room])

    if @room.save_new_room
      flash[:notice] = 'Sala creada exitosamente'
      redirect_to :administracion_rooms_list
    else
      @is_new = true
      render 'room'
    end
  end

  def edit
    @room = Room.find(params[:id])
    @is_new = false
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
    render 'room'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_rooms_list
    else
      @room = Room.find(params[:id])

      if @room.update_attributes(params[:room])
        flash.now[:notice] = 'Sala actualizada exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar la sala'
      end
      @is_new = false
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'room'
    end
  end
end

app/controllers/administracion/sectors_controller.rb
# -*- encoding : utf-8 -*-
class Administracion::SectorsController < ApplicationController
  def list
    @sectors = Sector.get_list.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @sector = Sector.new
    @is_new = true
    @available_zones = Sector.get_available_zones
    render 'sector'
  end

  def create
    @sector = Sector.new(params[:sector])

    if @sector.save
      flash[:notice] = 'Sector creado exitosamente'
      redirect_to :administracion_sectors_list
    else
      @is_new = true
      @available_zones = Sector.get_available_zones
      render 'sector'
    end
  end

  def edit
    @sector = Sector.find(params[:id])
    @is_new = false
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
    @available_zones = Sector.get_available_zones
    render 'sector'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_sectors_list
    else
      @sector = Sector.find(params[:id])

      if @sector.update_attributes(params[:sector])
        flash.now[:notice] = 'Sector actualizado exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar el sector'
      end
      @is_new = false
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      @available_zones = Sector.get_available_zones
      render 'sector'
    end
  end
end

app/controllers/administracion/users_controller.rb
# -*- encoding : utf-8 -*-
class Administracion::UsersController < ApplicationController
  def list
    @users = User.get_list.paginate(:page => params[:page], :per_page => 10)
    render 'index'
  end

  def new
    @user = User.new
    @is_new = true
    render 'user'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = 'Usuario creado exitosamente'
      redirect_to :administracion_users_list
    else
      @is_new = true
      render 'user'
    end
  end

  def edit
    @user = User.find(params[:id])
    @is_new = false
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
    render 'user'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_users_list
    else
      @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
        flash.now[:notice] = 'Usuario actualizado exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar al usuario'
      end
      @is_new = false
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'user'
    end
  end

  def password_change
    @user = User.find(params[:id])
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
  end

  def password_update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :administracion_users_list
    else
      @user = User.find(params[:id])
      pass = params[:user][:password]
      pass_conf = params[:user][:password_confirmation]
      if @user.update_attributes(password: pass , password_confirmation: pass_conf)
        flash.now[:notice] = 'Contraseña de usuario actualizada exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar la contraseña del usuario'
      end
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'password_change'
    end
  end
end

app/helpers/administracion/cleanup_requests_helper.rb
module Administracion::CleanupRequestsHelper
end

app/helpers/administracion/rooms_helper.rb
module Administracion::RoomsHelper
end

app/helpers/administracion/sectors_helper.rb
module Administracion::SectorsHelper
end

app/helpers/administration/administration_helper.rb
# -*- encoding : utf-8 -*-
module Administration::AdministrationHelper
end

app/views/administracion/administration/_legend_user_list.html.erb
<div class='legend-list-employees'>
  Leyenda: <i class="icon-pencil icon-black"></i> Editar |
  <i class="icon-edit icon-black"></i> Cambiar Contraseña
</div>

app/views/administracion/administration/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <h3>
      Lista de Usuarios
      <%= link_to administracion_new_path do%>
          <i class="icon-plus-sign no-underline"></i>
      <% end %>
    </h3>

    <br>

    <% if @users.blank? %>
        <h6>No se han encontrado usuarios</h6>
    <% else %>
        <table class='table table-striped table-bordered'>
          <tr>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Tipo</th>
            <th>Activo?</th>
            <th>Acciones</th>
          </tr>
          <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.last_name1 %></td>
                <td><%= user.last_name2 %></td>
                <td><%= user.get_user_type_str %></td>
                <td>
                  <% if user.active? %>
                      <i class="icon-ok icon-black"></i>
                  <% else %>
                      <i class="icon-remove icon-black"></i>
                  <% end %>
                </td>
                <td>
                  <%= link_to administracion_edit_path(user) do%>
                      <i class="icon-pencil icon-black"></i>
                  <% end %> |
                  <%= link_to administracion_password_change_path(user) do%>
                      <i class="icon-edit icon-black"></i>
                  <% end %>
                </td>
              </tr>
          <% end %>
        </table>
        <%= render 'legend_user_list' %>
        <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
    <% end %>
  </div>
</div>

app/views/administracion/administration/password_change.html.erb
<div class='fluid-row'>
  <div class='span12'>
    <h2>Cambio de Contraseña de <%= @user.complete_name %></h2>
  </div>
  <div class='span12'>
    <%= form_for @user, :url => administracion_password_update_path(@user) do |f|%>

        <%= render :partial => 'shared/model_errors',:object => @user, :as => 'token' %>

        <%= hidden_field_tag :sec, @sec %>

        <div class="control-group form-horizontal">
          <%= f.label :password, 'Nueva Contraseña', :class=>'control-label' %>
          <div class="controls">
            <%= f.password_field :password %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :password_confirmation, 'Confirmación de Contraseña', :class=>'control-label' %>
          <div class="controls">
            <%= f.password_field :password_confirmation %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <div class="controls">
            <%= f.submit 'Cambiar', :class => 'btn btn-primary' %>
            <%= link_to 'Volver a lista de usuarios', administracion_users_list_path, :class => 'btn btn-primary' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/administracion/administration/user.html.erb
<div class='fluid-row'>
  <div class='span12'>
    <h2><%= @is_new ? 'Nuevo Usuario' : 'Editando a '+@user.complete_name%></h2>
  </div>
  <div class='span12'>
    <% url_form = @is_new ? administracion_create_path : administracion_update_path(@user) %>
    <%= form_for @user, :url => url_form do |f|%>

        <%= render :partial => 'shared/model_errors',:object => @user, :as => 'token' %>

        <% unless @is_new %>
            <%= hidden_field_tag :sec, @sec %>
        <%end%>
        <div class="control-group form-horizontal">
          <%= f.label :name, 'Nombre', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :last_name1, 'Apellido Paterno', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :last_name1 %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :last_name2, 'Apellido Materno', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :last_name2 %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= label_tag :gender, 'Género', :class=>'control-label' %>
          <div class="controls">
            <%= f.radio_button(:gender, 'M', :checked => (@user.gender == 'M')) %> Masculino
            <%= f.radio_button(:gender, 'F', :checked => (@user.gender == 'F')) %> Femenino
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :active, 'Activo?', :class=>'control-label' %>
          <div class="controls">
            <%= f.check_box :active %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :user_type, 'Tipo de Usuario', :class=>'control-label' %>
          <div class="controls">
            <%= f.select :user_type,
                         options_for_select(User.user_type_options, @user.user_type),
                         {:prompt => 'Seleccione un tipo'}
            %>
          </div>
        </div>

        <div class="control-group form-horizontal">
          <%= f.label :username, 'Usuario', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :username %>
          </div>
        </div>
        <% if @is_new %>
            <div class="control-group form-horizontal">
              <%= f.label :password, 'Contraseña', :class=>'control-label' %>
              <div class="controls">
                <%= f.password_field :password %>
              </div>
            </div>

            <div class="control-group form-horizontal">
              <%= f.label :password_confirmation, 'Confirmación de Contraseña', :class=>'control-label' %>
              <div class="controls">
                <%= f.password_field :password_confirmation %>
              </div>
            </div>
        <% end %>

        <div>
            <% submit_str = @is_new ? 'Crear' : 'Actualizar' %>
            <%= f.submit submit_str, :class => 'btn btn-primary' %>
            <%= link_to 'Volver a lista', administracion_users_list_path, :class => 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>