config/routes.rb
# -*- encoding : utf-8 -*-
CUALimpieza::Application.routes.draw do

  get 'errors/not_found'
  get 'errors/server_error'
  get 'logs/show_since'

  namespace :limpieza do
    get 'general/index', :as => 'general'

    get 'agenda' => 'agenda#index', :as =>'agenda'
    get 'agenda/index' => 'agenda#index'
    get 'agenda/load_zone' => 'agenda#load_zone'
    #get_cleanup_request está hardcodeada en agenda.js.erb
    get 'agenda/get_cleanup_requests' => 'agenda#get_cleanup_request', :as => 'agenda_cleanup_request'
    get 'agenda/print_cleanup_requests', :as => 'print_cleanup_requests'
    get 'agenda/print_cleanup_requests_post', :as => 'print_cleanup_requests_post'
    get 'agenda/print_cleanup_requests_page', :as => 'print_cleanup_requests_page'

    post 'agenda/importar_excel' => 'agenda#import_excel', :as =>'import_excel'

    get 'calendario/index', :as =>'calendario'
    get 'calendario/get_events'
    # terminal cleanup
    get 'calendario/new', :as => 'new_terminal_cleanup'
    post 'calendario/create', :as => 'create_terminal_cleanup'
    get 'calendario/edit', :as => 'edit_terminal_cleanup'
    put 'calendario/update', :as => 'update_terminal_cleanup'
    delete 'calendario/destroy', :as => 'delete_terminal_cleanup'
    # terminal cleanup instance
    get 'calendario/new_tc_instance', :as => 'new_tc_instance'
    post 'calendario/create_tc_instance', :as => 'create_tc_instance'
    get 'calendario/edit_tc_instance', :as => 'edit_tc_instance'
    put 'calendario/update_tc_instance', :as => 'update_tc_instance'

    # Rooms view
    get 'vista_salas' => 'roomsView#index', :as =>'vista_salas'
    get 'vista_salas/index' => 'roomsView#index'

    get 'vista_salas/edit_room_status' => 'roomsView#edit_room_status' , :as => 'edit_room_status'
    put 'vista_salas/change_room_status' => 'roomsView#change_room_status' , :as => 'change_room_status'
    get 'vista_salas/edit_maintenance_room' => 'roomsView#edit_maintenance_room', :as => 'edit_maintenance_room'
    put 'vista_salas/finish_maintenance' => 'roomsView#finish_maintenance', :as => 'finish_maintenance'

    # Read-Only Rooms view
    get 'vista_salas/ver' => 'roomsView#show', :as => 'show_rooms_readonly'

    #Popups Cleanup Requests
    get 'popup_nueva_solicitud' => 'cleanup_popup#popup_cleanup_request_new', :as => 'new_cleanup_request'
    post 'crear_solicitud' => 'cleanup_popup#create', :as =>'create_cleanup_request'

    get 'popup_solicitud/:id' => 'cleanup_popup#popup_cleanup_request_show', :as => 'show_cleanup_request'
    post 'eliminar_solicitud' => 'cleanup_popup#delete', :as => 'delete_cleanup_request'
    put 'procesar_solicitud' => 'cleanup_popup#process_cleanup_request', :as => 'process_cleanup_request'
  end

  namespace :api do
    get 'rooms/sector/:id' => 'rooms#rooms_by_sector', :as => 'rooms_by_sector'
    get 'rooms/load_zone' => 'rooms#load_zone'
    get 'rooms/load_sector' => 'rooms#load_sector'
    resources :rooms
    get 'logs/show' => 'logs#show'
    get 'employees/:id' => 'employees#show'
    get 'employees/:id/vacations' => 'employees#employee_vacations'
  end

  namespace :personal do
    # Employees_Controller:
    get 'index' => 'employees#list', :as => 'employees_list'
    get 'nuevo_empleado' => 'employees#new', :as => 'new_employee'
    post 'crear_empleado' => 'employees#create', :as => 'create_employee'
    get 'editar_empleado/:id' => 'employees#edit', :as => 'edit_employee'
    put 'actualizar_empleado/:id' => 'employees#update', :as => 'update_employee'

    get 'historial_trabajo/:id' => 'employees#work_history', :as => 'work_history'
    get 'historial_limpieza/:id' => 'employees#cleaning_history', :as => 'cleaning_history'
    get 'asignar_turno/:id' => 'employees#assign_shift', :as => 'assign_shift'
    get 'get_shifts' => 'employees#get_shifts', :as => 'get_shifts'
    put 'update_shifts/:id' => 'employees#update_shifts', :as => 'update_shifts'

    #Shifts_Controller:
    get 'turnos' => 'shifts#index', :as => 'shifts'
    get 'turnos/nuevo_turno' => 'shifts#get_new_shift', :as => 'get_new_shift'
    get 'turnos/ver_turno' => 'shifts#get_shift', :as => 'get_shift'
    post 'turnos/crear_turno' => 'shifts#create', :as => 'create_shift'
    get 'shifts/shift_form', :as => 'shift_form'
    put 'turnos/actualizar/:id' => 'shifts#update', :as => 'update_shift'

    #Assistances_Controller:
    get 'asistencias' => 'assistances#index', :as => 'assistances'
    post 'asistencia_update' => 'assistances#update', :as => 'update'

    #Vacations controller:
    get 'vacaciones' => 'vacations#index', :as => 'vacations'
    get 'vacaciones/get_events' => 'vacations#get_events'
    get 'vacaciones/new' => 'vacations#new', :as => 'new_vacation'
    post 'vacaciones/create' => 'vacations#create', :as => 'create_vacation'
    get 'vacaciones/edit/:id' => 'vacations#edit', :as => 'edit_vacation'
    put 'vacaciones/edit/:id' => 'vacations#update', :as => 'update_vacation'
  end

  namespace :administracion do
    #--------------------------usuarios------------------------------
    get 'index' => 'users#list', :as => 'users_list'
    get 'usuarios/nuevo' => 'users#new', :as => 'new_user'
    post 'usuarios/crear' => 'users#create', :as => 'create_user'
    get 'usuarios/editar/:id' => 'users#edit', :as => 'edit_user'
    put 'usuarios/actualizar/:id' => 'users#update', :as => 'update_user'
    get 'usuarios/cambio_contrasena/:id' => 'users#password_change', :as =>'password_change'
    put 'usuarios/actualizar_contrasena/:id' => 'users#password_update', :as =>'password_update'

    #--------------------------salas------------------------------
    get 'salas/lista' => 'rooms#list', :as => 'rooms_list'
    get 'salas/nuevo' => 'rooms#new', :as => 'new_room'
    post 'salas/crear' => 'rooms#create', :as => 'create_room'
    get 'salas/editar/:id' => 'rooms#edit', :as => 'edit_room'
    put 'salas/actualizar/:id' => 'rooms#update', :as => 'update_room'

    #--------------------------sectores------------------------------
    get 'sectores/lista' => 'sectors#list', :as => 'sectors_list'
    get 'sectores/nuevo' => 'sectors#new', :as => 'new_sector'
    post 'sectores/crear' => 'sectors#create', :as => 'create_sector'
    get 'sectores/editar/:id' => 'sectors#edit', :as => 'edit_sector'
    put 'sectores/actualizar/:id' => 'sectors#update', :as => 'update_sector'

    #--------------------------solicitudes de limpieza------------------------------
    get 'solicitudes_limpieza/lista' => 'cleanup_requests#list', :as => 'cleanup_requests_list'
    get 'solicitudes_limpieza/ver/:id' => 'cleanup_requests#show', :as => 'cleanup_request_show'

  end

  get 'cambiar_contrasena' => 'home#my_password_change', :as =>'my_password_change'
  put 'actualizar_mi_contrasena' => 'home#my_password_update', :as =>'my_password_update'

  post 'home/login'  => 'home#login', :as => 'login'
  get 'home/logout'  => 'home#logout', :as => 'logout'

  #Paginas de error:
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'home#index'
end

app/controllers/limpieza/agenda_controller.rb
# -*- encoding : utf-8 -*-
class Limpieza::AgendaController < ApplicationController

  def index
    @zones = Sector.select(:zone).group(:zone).order(:name).map { |a| a.zone }
    @sectors = Sector.where(:zone => @zones[0]).order(:name)
    @date = Time.current  # TODO: deberia ser un parametro (giovanni)
  end

  def get_cleanup_request
    return render(:json => []) if params[:sector].blank?

    sector = Sector.find(params[:sector])
    start_date = Time.zone.at(params[:start].to_i)
    end_date =  Time.zone.at(params[:end].to_i)
    cleanup_requests = CleanupRequest.get_requests_from_sector(sector, start_date, end_date)
    @events = []
    cleanup_requests.each do |cleanup|
      @events << {
          id: "cleanup-#{cleanup.id}",
          start: cleanup.requested_at,
          allDay: false,
          title: cleanup.room.name + ' - ' + cleanup.get_request_type_str + ' : ' + cleanup.start_comments[0..20],
          className: "status-" + cleanup.status,
          popupUrl: limpieza_show_cleanup_request_path(id: cleanup.id),
          cleanupStatus: cleanup.status
      }
    end

    TerminalCleanup.get_instances(start_date, end_date, sector.id).each do |tci|
      @events << {
          id: "tc#{tci[:eventType]}-#{tci[:id]}",
          start: tci[:start],
          allDay: tci[:eventType] != 'instance',
          title: 'Aseo calendarizado: ' + tci[:title],
          className: "terminal-cleanup-#{tci[:eventType]}",
          popupUrl: tci[:eventType] == 'instance' ?
                        limpieza_edit_tc_instance_path + "?id=#{tci[:id]}" :
                        limpieza_new_tc_instance_path + "?tc_id=#{tci[:id]}",
          cleanupStatus: ''
      }
    end

    render :json => @events
  end

  def print_cleanup_requests
    @sectors = Sector.all
  end

  # POST
  def print_cleanup_requests_post
    # El primer elem de sector_id[] es vacio (magia rails >_>)
    if params[:sector_id] && params[:sector_id].count >= 2
      params[:sector_id].delete_at(0)

      params2 = { :sector_id => params[:sector_id], :date => params[:date] }
      @redirect = url_for(:action => :print_cleanup_requests_page) + '?' + params2.to_param
      render 'shared/modal_popup_redirect'
    else
      flash.now[:error] = 'Tiene que seleccionar al menos un sector.'
      @sectors = Sector.all
      render 'limpieza/agenda/print_cleanup_requests'
    end
  end

  def print_cleanup_requests_page
    ids = params[:sector_id].map { |x| x.to_i }
    @date = Time.zone.parse(params[:date])
    @sectors = Sector.where(:id => ids)
    @cleanup_requests = []
    @sectors.each do |s|
      @cleanup_requests[s.id] = CleanupRequest.get_requests_from_sector(s, @date, @date + 1.day)
    end

    render :layout => false
  end

  def import_excel
    begin
      if CleanupRequest.import_excel(@current_user, params[:excel])
        flash[:notice] = 'Se han creado las solicitudes de limpieza exitosamente desde el excel'
      else
        flash[:error] = 'Error al importar excel. Favor revisar formato de
                          archivo y exitencia de las salas en el sistema'
      end
    rescue Exception
      flash[:error] = 'Error al importar excel. Favor revisar formato de
                          archivo y exitencia de las salas en el sistema'
    end

    redirect_to :controller => 'limpieza/agenda', :action => :index
  end
end

app/controllers/limpieza/calendario_controller.rb
# -*- encoding : utf-8 -*-
require 'date'

class Limpieza::CalendarioController < ApplicationController
  # GET /limpieza/calendario
  def index
    @terminal_cleanups = TerminalCleanup.where('end_date is NULL')
  end

  # GET /limpieza/calendario/get_events
  def get_events
    if !params[:start].nil? and !params[:end].nil?
      # Importante usar Time para respetar huso horario
      start_date = Time.at(params[:start].to_i)
      end_date   = Time.at(params[:end].to_i)
      today = Date.today.to_time_in_current_zone
      @events = []

      # Calcular los aseos
      # TODO: Mover esta logica al modelo
      TerminalCleanup.find_each do |tc|
        rule_date = tc.start_date
        if rule_date < today
          # Primera fecha debe ser >= start_date
          while rule_date < start_date
            rule_date += tc.interval.days  # TODO: calc. iterativo no es eficiente
          end
        end

        # Cachear tci para evitar demasiadas consultas
        tci_collection = tc.terminal_cleanup_instances.where(:original_date => start_date .. end_date)

        rule_end_date = (tc.end_date or end_date)
        while rule_date <= rule_end_date
          # check terminal_cleanup_instances
          tci = tci_collection.find { |tc_instance| tc_instance.original_date == rule_date }
          if tci
            if tci.instance_date && tci.instance_date <= end_date
              # generado a partir de una instancia
              @events << {
                  :id => "instance-#{tci.id}",
                  :eventType => 'instance',
                  :start => tci.instance_date,
                  :title => tci.terminal_cleanup.name,
                  :className => ' cleanup-instance-finished'
              }
            else
              # es una excepcion
            end
          else
            # generado a partir de la regla
            @events << {
                :id => "rule-#{tc.id}",
                :eventType => 'rule',
                :start => rule_date,
                :allDay => true,
                :title => tc.name,
                :className => 'cleanup-rule'
            }
          end

          rule_date += tc.interval.days
        end
      end

      render :json => @events

    else
      render :json => {:error => 'start y end deben estar definidos'}, status: :unprocessable_entity
    end
  end


  # aseos terminales:

  #GET
  def new
    @terminal_cleanup = TerminalCleanup.new
    @terminal_cleanup.start_date = Time.current
    @sectors = Sector.all
    #@requestable_rooms = @sectors.first.rooms
    render 'limpieza/terminal_cleanup_popup/new'
  end

  #POST
  def create
    @terminal_cleanup = TerminalCleanup.new(params[:terminal_cleanup])
    if @terminal_cleanup.save
      render 'shared/modal_popup_success'
    else
      flash.now[:error] = 'No se ha podido crear el aseo terminal'
      @sectors = Sector.all
      #@requestable_rooms = @sectors.first.rooms
      render 'limpieza/terminal_cleanup_popup/new'
    end
  end

  #GET (no utilizado aun)
  def edit
    @terminal_cleanup = TerminalCleanup.find(params[:id])
    #render :json => @terminal_cleanup
    @requestable_rooms = Room.all
    render 'limpieza/terminal_cleanup_popup/edit'
  end

  #PUT (no utilizado aun)
  def update
    @terminal_cleanup = TerminalCleanup.find(params[:terminal_cleanup][:id])
    if @terminal_cleanup.update_attributes(params[:terminal_cleanup])
      render 'shared/modal_popup_success'
    else
      flash.now[:error] = 'No se ha podido crear el aseo terminal'
      render 'limpieza/terminal_cleanup_popup/edit'
    end
  end

  #DELETE
  def destroy
    @terminal_cleanup = TerminalCleanup.find(params[:id])
    @terminal_cleanup.end_date = Time.zone.today

    respond_to do |format|
      if @terminal_cleanup.save
        format.html { redirect_to :action => :index }
        format.json { render 'shared/modal_popup_success' }
      end
    end
  end


  # terminal cleanup instances :

  #GET
  def new_tc_instance
    @terminal_cleanup = TerminalCleanup.find(params[:tc_id])
    if @terminal_cleanup
      @terminal_cleanup_instance = TerminalCleanupInstance.new
      @terminal_cleanup_instance.terminal_cleanup = @terminal_cleanup
      if params[:tc_year] && params[:tc_month] && params[:tc_day]
        @terminal_cleanup_instance.original_date = Time.zone.parse("#{params[:tc_year]}-#{params[:tc_month]}-#{params[:tc_day]}")
      else
        @terminal_cleanup_instance.original_date = Time.zone.today
      end
        @terminal_cleanup_instance.instance_date = Time.current

      render 'limpieza/terminal_cleanup_popup/new_tc_instance'
    else
      render :text => "Aseo terminal #{:tc_id} no encontrado"
    end
  end

  #POST
  def create_tc_instance
    @terminal_cleanup_instance = TerminalCleanupInstance.new(params[:terminal_cleanup_instance])

    if @terminal_cleanup_instance.create_with_log(@current_user)
      render 'shared/modal_popup_success'
    else
      flash.now[:error] = 'No se ha podido crear el aseo terminal'
      render 'limpieza/terminal_cleanup_popup/new_tc_instance'
    end
  end

  #GET
  def edit_tc_instance
    @terminal_cleanup_instance = TerminalCleanupInstance.find(params[:id])
    render 'limpieza/terminal_cleanup_popup/edit_tc_instance'
  end

  #PUT
  def update_tc_instance
    @terminal_cleanup_instance = TerminalCleanupInstance.find(params[:terminal_cleanup_instance][:id])
    if @terminal_cleanup_instance.update_with_log(@current_user, params[:terminal_cleanup_instance])
      render 'shared/modal_popup_success'
    else
      flash.now[:error] = 'No se ha podido crear el aseo terminal'
      render 'limpieza/terminal_cleanup_popup/edit_tc_instance'
    end
  end

end

app/helpers/limpieza/calendario_helper.rb
# -*- encoding : utf-8 -*-
module Limpieza::CalendarioHelper
end

app/helpers/limpieza/cleanup_popup_helper.rb
# -*- encoding : utf-8 -*-
module Limpieza::CleanupPopupHelper
end

app/helpers/limpieza/general_helper.rb
# -*- encoding : utf-8 -*-
module Limpieza::GeneralHelper
end

app/views/limpieza/terminal_cleanup_popup/edit.erb
<div class="modal-header">
  <h1>Editar Aseo Terminal</h1>
</div>
<%= form_for @terminal_cleanup, :url => limpieza_update_terminal_cleanup_path, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="modal-body">
      <%= bootstrap_flash %>
      <%= render :partial => 'shared/model_errors', :object => @terminal_cleanup, :as => 'token' %>

      <%= f.hidden_field :id %>

      <div class="control-group">
        <%= label_tag :room_id, 'Sala', :class => 'control-label' %>
        <div class="controls">
          <%= f.collection_select :room_id, @requestable_rooms, :id, :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :start_date, 'Fecha inicio', :class => "control-label" %>
        <div class="controls">
          <div class="datetimepicker input-append date">
            <%= f.text_field :start_date, :value => @terminal_cleanup.start_date.strftime("%d-%m-%Y") %>
            <span class="add-on">
                      <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                </span>
          </div>
        </div>

      </div>

      <div class="control-group">
        <%= f.label :interval, 'Intervalo', :class => "control-label" %>
        <div class="controls">
          <%= f.number_field :interval, :min => 0 %>
          días
        </div>
      </div>

      <div class="control-group">
        <%= f.label :comments, 'Comentarios', :class => "control-label" %>
        <div class="controls">
          <%= f.text_area :comments %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Guardar cambios', :class => 'btn btn-primary' %>
      <%= link_to 'Cerrar', '#', :class => 'btn', 'data-dismiss' => 'modal' %>
    </div>
<% end %>

app/views/limpieza/terminal_cleanup_popup/edit_tc_instance.html.erb
<div class="modal-header">
  <h1>Modificar Aseo Agendado</h1>
</div>
<%= form_for @terminal_cleanup_instance, :url => limpieza_update_tc_instance_path, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="modal-body">
      <%= bootstrap_flash %>
      <%= render :partial => 'shared/model_errors', :object => @terminal_cleanup_instance, :as => 'token' %>

      <%= f.hidden_field :id %>

      <div class="control-group">
        <%= label_tag nil, 'Lugar', :class => 'control-label' %>
        <div class="controls">
          <span class="uneditable-input">
            <%= @terminal_cleanup_instance.terminal_cleanup.name %>
          </span>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Fecha fijada</label>

        <div class="controls">
          <span class="uneditable-input">
            <%= @terminal_cleanup_instance.original_date.strftime("%d-%m-%Y") %>
          </span>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :instance_date, 'Fecha realización', :class => "control-label" %>
        <div class="controls">
          <div class="datetimepicker input-append date">
            <%= f.text_field :instance_date, :value => @terminal_cleanup_instance.formatted_instance_date %>
            <span class="add-on">
              <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Comentarios de la regla</label>
        <div class="controls">
          <p><%= @terminal_cleanup_instance.terminal_cleanup.comments %></p>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :comments, 'Comentarios de esta fecha', :class => "control-label" %>
        <div class="controls">
          <%= f.text_area :comments %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Actualizar', :class => 'btn btn-primary' %>
      <%= f.submit 'Eliminar', :id => 'btn-delete', :class =>'btn btn-danger pull-left' %>
      <%= link_to 'Cancelar', '#', :class => 'btn', 'data-dismiss' => 'modal' %>
    </div>
<% end %>

<script>
    $('#btn-delete').on('click', function () {
        $('#terminal_cleanup_instance_instance_date')
                .val('');
    });
</script>

app/views/limpieza/terminal_cleanup_popup/new.erb
<div class="modal-header">
  <h1>Nueva Regla de Aseo</h1>
</div>
<%= form_for @terminal_cleanup, :url => limpieza_create_terminal_cleanup_path, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="modal-body">
      <%= bootstrap_flash %>
      <%= render :partial => 'shared/model_errors', :object => @terminal_cleanup, :as => 'token' %>

      <div class="control-group">
        <%= label_tag :sector_id, 'Sector', :class => 'control-label' %>
        <div class="controls">
          <%= f.collection_select :sector_id, @sectors, :id, :name, { :include_blank => true } %>
        </div>
      </div>

      <div class="control-group">
        <%= label_tag :room_id, 'Sala', :class => 'control-label' %>
        <div class="controls">
          <select id="terminal_cleanup_room_id" name="terminal_cleanup[room_id]">
            <%# select rellenado con javascript... %>
          </select>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :start_date, 'Fecha inicio', :class => "control-label" %>
        <div class="controls">
          <div class="datepicker input-append date">
            <%= f.text_field :start_date, :value => @terminal_cleanup.start_date ? @terminal_cleanup.start_date.strftime("%d-%m-%Y") : '' %>
            <span class="add-on">
                      <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                </span>
          </div>
        </div>

      </div>

      <div class="control-group">
        <%= f.label :interval, 'Intervalo', :class => "control-label" %>
        <div class="controls">
          <%= f.number_field :interval, :min => 0 %>
          días
        </div>
      </div>

      <div class="control-group">
        <%= f.label :comments, 'Comentarios', :class => "control-label" %>
        <div class="controls">
          <%= f.text_area :comments %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Crear aseo', :class => 'btn btn-primary' %>
      <%= link_to 'Cerrar', '#', :class => 'btn', 'data-dismiss' => 'modal' %>
    </div>
<% end %>

<script>
    $(function() {
        // actualizar el select de Salas al cambiar el Sector
        $('#terminal_cleanup_sector_id').change(loadRoomSelect);
        loadRoomSelect();
    });

    function loadRoomSelect() {
        var sector_id = $('#terminal_cleanup_sector_id').val();
        if (sector_id) {
            var $room_select = $('#terminal_cleanup_room_id');
            $room_select.html('');  // clear options
            $room_select.append('<option value="">Cargando...</option>');

            $.getJSON('/api/rooms/sector/:id.json'.replace(':id', sector_id),
                    function(data) {
                        $room_select.html('');  // clear options
                        $room_select.append('<option value="">Todas las de '+
                                $('#terminal_cleanup_sector_id option:selected').text() +
                                '</option>');
                        for (var i = 0; i < data.length; i++) {
                            var $option = $('<option></option>');
                            $option.val(data[i]['id']);
                            $option.text(data[i]['name']);
                            $room_select.append($option);
                        }
                    });
        }
        else {
            $('#terminal_cleanup_room_id').html('<optgroup label="Elija un sector..."></optgroup>');
        }
    }
</script>

app/views/limpieza/terminal_cleanup_popup/new_tc_instance.erb
<div class="modal-header">
  <h1>Agendar Aseo</h1>
</div>
<%= form_for @terminal_cleanup_instance, :url => limpieza_create_tc_instance_path, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="modal-body">
      <%= bootstrap_flash %>
      <%= render :partial => 'shared/model_errors', :object => @terminal_cleanup_instance, :as => 'token' %>

      <%= f.hidden_field :terminal_cleanup_id %>
      <%= f.hidden_field :original_date %>

      <div class="control-group">
        <%= label_tag nil, 'Lugar', :class => 'control-label' %>
        <div class="controls">
          <span class="uneditable-input">
            <%= @terminal_cleanup_instance.terminal_cleanup.name %>
          </span>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Fecha fijada</label>

        <div class="controls">
          <span class="uneditable-input">
            <%= @terminal_cleanup_instance.original_date.strftime("%d-%m-%Y") %>
          </span>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :instance_date, 'Fecha realización', :class => "control-label" %>
        <div class="controls">
          <div class="datetimepicker input-append date">
            <%= f.text_field :instance_date, :value => @terminal_cleanup_instance.formatted_instance_date %>
            <span class="add-on">
              <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Comentarios de la regla</label>

        <div class="controls">
          <p><%= @terminal_cleanup_instance.terminal_cleanup.comments %></p>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :comments, 'Comentarios de esta fecha', :class => "control-label" %>
        <div class="controls">
          <%= f.text_area :comments %>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
      <%= f.submit 'Eliminar', :id => 'btn-delete', :class =>'btn btn-danger pull-left' %>
      <%= link_to 'Cancelar', '#', :class => 'btn', 'data-dismiss' => 'modal' %>
    </div>
<% end %>

<script>
    $('#btn-delete').on('click', function () {
        $('#terminal_cleanup_instance_instance_date')
                .prop('disabled', true);
    });
</script>