config/routes.rb
# -*- encoding : utf-8 -*-
CUALimpieza::Application.routes.draw do

  get 'errors/not_found'
  get 'errors/server_error'
  get 'logs/show_since'

  namespace :limpieza do
    get 'general/index', :as => 'general'

    get 'agenda' => 'agenda#index', :as =>'agenda'
    get 'agenda/index' => 'agenda#index'
    get 'agenda/load_zone' => 'agenda#load_zone'
    #get_cleanup_request está hardcodeada en agenda.js.erb
    get 'agenda/get_cleanup_requests' => 'agenda#get_cleanup_request', :as => 'agenda_cleanup_request'
    get 'agenda/print_cleanup_requests', :as => 'print_cleanup_requests'
    get 'agenda/print_cleanup_requests_post', :as => 'print_cleanup_requests_post'
    get 'agenda/print_cleanup_requests_page', :as => 'print_cleanup_requests_page'

    post 'agenda/importar_excel' => 'agenda#import_excel', :as =>'import_excel'

    get 'calendario/index', :as =>'calendario'
    get 'calendario/get_events'
    # terminal cleanup
    get 'calendario/new', :as => 'new_terminal_cleanup'
    post 'calendario/create', :as => 'create_terminal_cleanup'
    get 'calendario/edit', :as => 'edit_terminal_cleanup'
    put 'calendario/update', :as => 'update_terminal_cleanup'
    delete 'calendario/destroy', :as => 'delete_terminal_cleanup'
    # terminal cleanup instance
    get 'calendario/new_tc_instance', :as => 'new_tc_instance'
    post 'calendario/create_tc_instance', :as => 'create_tc_instance'
    get 'calendario/edit_tc_instance', :as => 'edit_tc_instance'
    put 'calendario/update_tc_instance', :as => 'update_tc_instance'

    # Rooms view
    get 'vista_salas' => 'roomsView#index', :as =>'vista_salas'
    get 'vista_salas/index' => 'roomsView#index'

    get 'vista_salas/edit_room_status' => 'roomsView#edit_room_status' , :as => 'edit_room_status'
    put 'vista_salas/change_room_status' => 'roomsView#change_room_status' , :as => 'change_room_status'
    get 'vista_salas/edit_maintenance_room' => 'roomsView#edit_maintenance_room', :as => 'edit_maintenance_room'
    put 'vista_salas/finish_maintenance' => 'roomsView#finish_maintenance', :as => 'finish_maintenance'

    # Read-Only Rooms view
    get 'vista_salas/ver' => 'roomsView#show', :as => 'show_rooms_readonly'

    #Popups Cleanup Requests
    get 'popup_nueva_solicitud' => 'cleanup_popup#popup_cleanup_request_new', :as => 'new_cleanup_request'
    post 'crear_solicitud' => 'cleanup_popup#create', :as =>'create_cleanup_request'

    get 'popup_solicitud/:id' => 'cleanup_popup#popup_cleanup_request_show', :as => 'show_cleanup_request'
    post 'eliminar_solicitud' => 'cleanup_popup#delete', :as => 'delete_cleanup_request'
    put 'procesar_solicitud' => 'cleanup_popup#process_cleanup_request', :as => 'process_cleanup_request'
  end

  namespace :api do
    get 'rooms/sector/:id' => 'rooms#rooms_by_sector', :as => 'rooms_by_sector'
    get 'rooms/load_zone' => 'rooms#load_zone'
    get 'rooms/load_sector' => 'rooms#load_sector'
    resources :rooms
    get 'logs/show' => 'logs#show'
    get 'employees/:id' => 'employees#show'
    get 'employees/:id/vacations' => 'employees#employee_vacations'
  end

  namespace :personal do
    # Employees_Controller:
    get 'index' => 'employees#list', :as => 'employees_list'
    get 'nuevo_empleado' => 'employees#new', :as => 'new_employee'
    post 'crear_empleado' => 'employees#create', :as => 'create_employee'
    get 'editar_empleado/:id' => 'employees#edit', :as => 'edit_employee'
    put 'actualizar_empleado/:id' => 'employees#update', :as => 'update_employee'

    get 'historial_trabajo/:id' => 'employees#work_history', :as => 'work_history'
    get 'historial_limpieza/:id' => 'employees#cleaning_history', :as => 'cleaning_history'
    get 'asignar_turno/:id' => 'employees#assign_shift', :as => 'assign_shift'
    get 'get_shifts' => 'employees#get_shifts', :as => 'get_shifts'
    put 'update_shifts/:id' => 'employees#update_shifts', :as => 'update_shifts'

    #Shifts_Controller:
    get 'turnos' => 'shifts#index', :as => 'shifts'
    get 'turnos/nuevo_turno' => 'shifts#get_new_shift', :as => 'get_new_shift'
    get 'turnos/ver_turno' => 'shifts#get_shift', :as => 'get_shift'
    post 'turnos/crear_turno' => 'shifts#create', :as => 'create_shift'
    get 'shifts/shift_form', :as => 'shift_form'
    put 'turnos/actualizar/:id' => 'shifts#update', :as => 'update_shift'

    #Assistances_Controller:
    get 'asistencias' => 'assistances#index', :as => 'assistances'
    post 'asistencia_update' => 'assistances#update', :as => 'update'

    #Vacations controller:
    get 'vacaciones' => 'vacations#index', :as => 'vacations'
    get 'vacaciones/get_events' => 'vacations#get_events'
    get 'vacaciones/new' => 'vacations#new', :as => 'new_vacation'
    post 'vacaciones/create' => 'vacations#create', :as => 'create_vacation'
    get 'vacaciones/edit/:id' => 'vacations#edit', :as => 'edit_vacation'
    put 'vacaciones/edit/:id' => 'vacations#update', :as => 'update_vacation'
  end

  namespace :administracion do
    #--------------------------usuarios------------------------------
    get 'index' => 'users#list', :as => 'users_list'
    get 'usuarios/nuevo' => 'users#new', :as => 'new_user'
    post 'usuarios/crear' => 'users#create', :as => 'create_user'
    get 'usuarios/editar/:id' => 'users#edit', :as => 'edit_user'
    put 'usuarios/actualizar/:id' => 'users#update', :as => 'update_user'
    get 'usuarios/cambio_contrasena/:id' => 'users#password_change', :as =>'password_change'
    put 'usuarios/actualizar_contrasena/:id' => 'users#password_update', :as =>'password_update'

    #--------------------------salas------------------------------
    get 'salas/lista' => 'rooms#list', :as => 'rooms_list'
    get 'salas/nuevo' => 'rooms#new', :as => 'new_room'
    post 'salas/crear' => 'rooms#create', :as => 'create_room'
    get 'salas/editar/:id' => 'rooms#edit', :as => 'edit_room'
    put 'salas/actualizar/:id' => 'rooms#update', :as => 'update_room'

    #--------------------------sectores------------------------------
    get 'sectores/lista' => 'sectors#list', :as => 'sectors_list'
    get 'sectores/nuevo' => 'sectors#new', :as => 'new_sector'
    post 'sectores/crear' => 'sectors#create', :as => 'create_sector'
    get 'sectores/editar/:id' => 'sectors#edit', :as => 'edit_sector'
    put 'sectores/actualizar/:id' => 'sectors#update', :as => 'update_sector'

    #--------------------------solicitudes de limpieza------------------------------
    get 'solicitudes_limpieza/lista' => 'cleanup_requests#list', :as => 'cleanup_requests_list'
    get 'solicitudes_limpieza/ver/:id' => 'cleanup_requests#show', :as => 'cleanup_request_show'

  end

  get 'cambiar_contrasena' => 'home#my_password_change', :as =>'my_password_change'
  put 'actualizar_mi_contrasena' => 'home#my_password_update', :as =>'my_password_update'

  post 'home/login'  => 'home#login', :as => 'login'
  get 'home/logout'  => 'home#logout', :as => 'logout'

  #Paginas de error:
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'home#index'
end

app/controllers/api/employees_controller.rb
# -*- encoding : utf-8 -*-
class Api::EmployeesController < ApplicationController
  include ApplicationHelper

  # GET /api/employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.json { render json: @employee }
    end
  end

  # GET /api/employees/1/vacations.json
  # Retorna los dias de vacaciones que ha tomado este empleado desde 01/Enero
  def employee_vacations
    #vacaciones de este año
    vacations = Employee.find(params[:id]).get_vacation_days

    respond_to do |format|
      format.json { render json: vacations }
    end
  end
  
end

app/controllers/personal/assistances_controller.rb
# -*- encoding : utf-8 -*-
class Personal::AssistancesController < ApplicationController
  def index
    @date = Time.zone.parse(params[:date]) if params[:date]
    @date = Time.current.beginning_of_day if @date.nil?

    @shifts = Shift.all
    @shift = Shift.find(params[:shift_id]) unless params[:shift_id].blank?
    if @shift and @shift.active_date_for_shift?(@date)
      # recuperar registros de asistencia
      @assistances = Assistance.where(:date => @date).where(:shift_id => @shift.id)

      # Si no existen, autogenerar registros de asistencia para ese día
      # Nota: Se generan incluso si estan de vacaciones (eso se distingue en la vista)
      if @assistances.length == 0
        @shift.employees.each do |e|
          a = Assistance.create(date: @date, start_time: @shift.start_time, end_time: @shift.end_time,
                                employee_id: e.id, shift_id: @shift.id)
          @assistances << a
        end
      end

      # ordenar asistencia por apellido empleado
      @assistances.sort! { |x,y| x.employee.last_name1 <=> y.employee.last_name1 }
    end

    # No editar asistencias muy en el pasado
    @editable = (Time.current.beginning_of_day - @date) <= 2.days
  end

  # POST
  def update
    assistance = ((Assistance.find(params[:id]) if params[:id]) or nil)
    time = params[:time]
    if assistance
      assistance.entry_time = Time.zone.parse(time)
      assistance.save!
    end

    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/controllers/personal/employees_controller.rb
# -*- encoding : utf-8 -*-
class Personal::EmployeesController < ApplicationController
  def list
    @employees = Employee.get_list.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @employee = Employee.new
    @is_new = true
    render 'employee'
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      flash[:notice] = 'Empleado creado exitosamente'
      redirect_to :controller => 'personal/employees', :action => 'list'
    else
      @is_new = true
      render 'employee'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @is_new = false
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
    render 'employee'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash[:error] = 'ERROR: No se debe cambiar el formulario'
      redirect_to :controller=>'personal/employees', :action => 'list'
    else
      @employee = Employee.find(params[:id])

      if @employee.update_attributes(params[:employee])
        flash.now[:notice] = 'Empleado actualizado exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar al empleado'
      end
      @is_new = false
      @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      render 'employee'
    end
  end

  def work_history
    @employee = Employee.find(params[:id])
    @employee_work_history = @employee.get_work_history.paginate(:page => params[:page], :per_page => 10)
  end

  def cleaning_history
    @employee = Employee.find(params[:id])
    @employee_cleaning_history = @employee.get_cleaning_history.paginate(:page => params[:page], :per_page => 10)
  end

  def assign_shift
    @employee = Employee.find(params[:id])
    @shifts = Shift.all
  end

  #Ajax
  def get_shifts
    employee = Employee.find(params[:id])
    @shifts = []

    employee.shifts.each do |shift|
      start_times = []
      end_times = []
      started_hour = Time.zone.at(shift.start_time)
      end_hour = Time.zone.at(shift.start_time)
      shift.get_days_of_the_week.each do |day|
        start_times << day + started_hour.hour * 3600 + started_hour.min * 60
        end_times << day + end_hour.hour * 3600 + end_hour.min * 60
      end
      @shifts << {
          id: shift.id,
          allDay: false,
          title: shift.name,
          start_times: start_times,
          end_times: end_times
      }
    end

    render :json => @shifts
  end

  def update_shifts
    @employee = Employee.find(params[:id])
    shifts = Shift.where(["id in (?)", params[:assign_shift_collection]])

    #Se agregan los turnos nuevos
    shifts.each do |shift|
      unless @employee.shifts.include?(shift)
        @employee.shifts << shift
      end
    end

    #Se eliminan los turnos no borrados
    @employee.shifts = @employee.shifts.select {|shift| shifts.include? shift}
    if @employee.save
      flash.now[:notice] = "Lista de turnos actualizada correctamente."
    else
      flash.now[:error] = "Ha ocurrido un error al intentar guardar la lista de turnos"
    end

    redirect_to controller: 'personal/employees', action: 'assign_shift', id: @employee.id
  end

end

app/controllers/personal/shifts_controller.rb
# -*- encoding : utf-8 -*-
class Personal::ShiftsController < ApplicationController
  def index
    @shifts = Shift.all
  end

  def create
    @shift = Shift.new(params[:shift])
    if @shift.save
      flash.now[:notice] = 'Turno creado exitosamente'
    else
      flash.now[:error] = 'Error al crear el nuevo turno'
    end

    redirect_to controller: 'personal/shifts', action: 'index'
  end

  def update
    if params[:sec] != Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))
      flash.now[:error] = 'ERROR: No se debe cambiar el formulario'
    else
      @shift = Shift.find(params[:id])
      if @shift.update_attributes(params[:shift])

        @shift.save
        flash.now[:notice] = 'Turno actualizado exitosamente'
      else
        flash.now[:error] = 'No se ha podido actualizar el turno'
      end
    end

    redirect_to controller: 'personal/shifts', action: 'index'
  end

  def get_new_shift
    @shift = Shift.new
    @url_form = personal_create_shift_path()
    @name = "nuevo turno"
    @submit_str = "Crear"

    render personal_shift_form_path
  end

  def get_shift
    @shift = Shift.find(params[:id])
    @url_form = personal_update_shift_path(@shift)
    @name = @shift.name
    @submit_str = "Actualizar"
    @sec = Digest::SHA1.hexdigest(Digest::SHA1.hexdigest(@current_user.id.to_s+'_'+params[:id]))

    render personal_shift_form_path
  end
end

app/controllers/personal/vacations_controller.rb
class Personal::VacationsController < ApplicationController
  def index
  end

  # GET (JSON)
  def get_events
    if !params[:start].nil? and !params[:end].nil?
      # Importante usar Time para respetar huso horario
      start_date = Time.at(params[:start].to_i)
      end_date   = Time.at(params[:end].to_i)
      today = Date.today.to_time_in_current_zone
      @events = []

      # Obtener vacaciones
      Vacation.where('start_date <= ?', end_date)
              .where('end_date >= ?', start_date)
              .each do |v|
        @events << {
            :id => "vacation-#{v.id}",
            :eventType => v.vacation_type,
            :start => v.start_date,
            :end => v.end_date,
            :title => v.employee.complete_name,
            :className => 'cal-'  + v.vacation_type,
        }
      end

      render :json => @events
    else
      render :json => {:error => 'start y end deben estar definidos'}, status: :unprocessable_entity
    end
  end

  #GET
  def new
    @vacation = Vacation.new
    @employees = Employee.all
  end

  #POST
  def create
    @vacation = Vacation.new(params[:vacation])
    if @vacation.save
      render 'shared/modal_popup_success'
    else
      flash.now[:error] = 'No se ha podido crear el registro'
      @employees = Employee.all
      render 'new'
    end
  end

  # GET
  def edit
    @vacation = Vacation.find(params[:id])
  end

  # PUT
  def update
    @vacation = Vacation.find(params[:id])
    if params[:submit_type] != 'delete'
      if @vacation.update_attributes(params[:vacation])
        render 'shared/modal_popup_success'
      else
        render 'edit'
      end
    else
      @vacation.destroy
      render 'shared/modal_popup_success'
    end
  end
end

app/helpers/personal/assitances_helper.rb
# -*- encoding : utf-8 -*-
module Personal::AssitancesHelper
end

app/helpers/personal/employees_helper.rb
# -*- encoding : utf-8 -*-
module Personal::EmployeesHelper
end

app/helpers/personal/shifts_helper.rb
# -*- encoding : utf-8 -*-
module Personal::ShiftsHelper
end

app/helpers/personal/vacations_helper.rb
module Personal::VacationsHelper
end

app/views/personal/employees/_legend_list.html.erb
<div class='legend-list-employees'>
  Leyenda: <i class="icon-pencil icon-black"></i> Editar |
  <i class="icon-briefcase icon-black"></i> Historial de Trabajo |
  <i class="icon-list-alt icon-black"></i> Historial de Limpieza |
  <i class="icon-tag icon-black"></i> Asignar Turno
</div>

app/views/personal/employees/assign_shift.html.erb
<h3>Horario semanal de <%= @employee.name %></h3>

<div id="shift_assign_calendar" data-id="<%= @employee.id %>" class="row-fluid">

</div>
<%= form_for @employee, url: personal_update_shifts_path(@employee), html: {class: "selection_shift_form row-fluid"} do |f| %>
  <%= label_tag :assign_shift_collection, "Lista de turnos asignados" %>
  <%= select_tag :assign_shift_collection, options_from_collection_for_select(@shifts, "id", "name"),
                   multiple: true %>
  <%= f.submit "Actualizar", name: "Actualizar", class: "btn btn-primary"%>
<% end %>

app/views/personal/employees/employee.html.erb
<div class='fluid-row'>
  <div class='span12'>
    <% @page_title = @is_new ? 'Nuevo Empleado' : 'Editando Empleado '%>
    <ul class="breadcrumb">
      <li><a href=<%= personal_employees_list_path %>>Lista de Empleados</a> <span class="divider">/</span></li>
      <li class="active"><%= @page_title %></li>
    </ul>
    <% @page_title = @is_new ? 'Nuevo Empleado' : 'Editando a '+@employee.complete_name %>
    <h2><%= @page_title %></h2>
  </div>
  <div class='span12'>
    <% url_form = @is_new ? personal_create_employee_path : personal_update_employee_path(@employee) %>
    <%= form_for @employee, :url => url_form do |f|%>
        <% unless @is_new %>
            <%= hidden_field_tag :sec, @sec %>
        <%end%>

        <%= render :partial => 'shared/model_errors',:object => @employee, :as => 'token' %>

        <div class="accordion" id="accordion_employee">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_employee" href="#collapseOne">
                Datos Personales
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
              <div class="accordion-inner">
                <div class="control-group form-horizontal">
                  <%= f.label :name, 'Nombre', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :name %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :last_name1, 'Apellido Paterno', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :last_name1 %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :last_name2, 'Apellido Materno', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :last_name2 %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= label_tag :gender, 'Género', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.radio_button(:gender, 'M', :checked => (@employee.gender == 'M')) %> Masculino
                    <%= f.radio_button(:gender, 'F', :checked => (@employee.gender == 'F')) %> Femenino
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :marital_status, 'Estado Civil', :class=>"control-label" %>
                  <div class="controls">
                    <%= f.select :marital_status,
                                 options_for_select(Employee.marital_status_options, @employee.marital_status),
                                 {:prompt => 'Seleccione un estado'}
                    %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :education_level, 'Formación Académica', :class=>"control-label" %>
                  <div class="controls">
                    <%= f.select :education_level,
                                 options_for_select(Employee.education_level_options, @employee.education_level),
                                 {:prompt => 'Seleccione un nivel'}
                    %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :birth_date, 'Fecha de nacimiento', :class=>"control-label" %>
                  <div class="controls">
                    <div class="datepicker input-append date">
                      <%= f.text_field :birth_date%>
                      <span class="add-on">
                         <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :religion, 'Religión', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :religion %>
                  </div>
                </div>

              </div>
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_employee" href="#collapseTwo">
                Datos Familiares
              </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
              <div class="accordion-inner">

                <div class="control-group form-horizontal">
                  <%= f.label :spouse_name, 'Nombre Cónyuge', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :spouse_name %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :spouse_occupation, 'Ocupación Cónyuge', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.text_field :spouse_occupation %>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :children, 'Número de Hijos', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.number_field :children, :min => 0 %>
                  </div>
                </div>

              </div>
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_employee" href="#collapseThree">
                Datos Laborales
              </a>
            </div>
            <div id="collapseThree" class="accordion-body collapse">
              <div class="accordion-inner">

                <div class="control-group form-horizontal">
                  <%= label_tag 'employee[occupation_id]', 'Ocupación', :class=>"control-label" %>
                  <div class="controls">
                    <%= select_tag 'employee[occupation_id]',
                                 options_for_select(Employee.occupation_options, @employee.occupation_id),
                                 {:prompt => 'Seleccione una ocupación'}%>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :joined_at, 'Ingreso', :class=>"control-label" %>
                  <div class="controls">
                    <div class="datepicker input-append date">
                      <%= f.text_field :joined_at%>
                      <span class="add-on">
                         <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :uniform_date, 'Entrega de Uniforme', :class=>"control-label" %>
                  <div class="controls">
                    <div class="datepicker input-append date">
                      <%= f.text_field :uniform_date%>
                      <span class="add-on">
                         <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :equipment_date, 'Entrega de Equipo', :class=>"control-label" %>
                  <div class="controls">
                    <div class="datepicker input-append date">
                      <%= f.text_field :equipment_date%>
                      <span class="add-on">
                         <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
                      </span>
                    </div>
                  </div>
                </div>

                <div class="control-group form-horizontal">
                  <%= f.label :training, 'Asistió a capacitación?', :class=>'control-label' %>
                  <div class="controls">
                    <%= f.check_box :training %>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        <% submit_str = @is_new ? 'Crear' : 'Actualizar' %>
        <%= f.submit submit_str, :class => 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>

app/views/personal/employees/list.html.erb
<div class="row-fluid">
    <div class="span12">
        <h3>
          Lista de Empleados
          <%= link_to personal_new_employee_path do%>
              <i class="icon-plus-sign no-underline"></i>
          <% end %>
        </h3>

        <br>

        <%= render partial: 'shared/search_form',
                 locals: {action_url: personal_employees_list_path,
                          current_search: params[:search],
                          search_label: 'Buscar Empleado'} %>

        <% if @employees.blank? %>
          <div class="alert alert-info text-center">
            <h6>No se han creado empleados</h6>
          </div>
        <% else %>
            <table class='table table-striped table-bordered'>
                <tr>
                    <th>Ap. Paterno</th>
                    <th>Ap. Materno</th>
                    <th>Nombre</th>
                    <th>Cargo</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
              <% @employees.each do |employee| %>
                  <tr>
                    <td><%= employee.last_name1 %></td>
                    <td><%= employee.last_name2 %></td>
                    <td><%= employee.name %></td>
                    <td><%= employee.get_occupation %></td>
                    <td><%= employee.get_status %></td>
                    <td>
                      <%= link_to personal_edit_employee_path(employee) do%>
                          <i class="icon-pencil icon-black"></i>
                      <% end %> |
                      <%= link_to personal_work_history_path(employee) do%>
                          <i class="icon-briefcase icon-black"></i>
                      <% end %> |
                      <%= link_to personal_cleaning_history_path(employee) do%>
                          <i class="icon-list-alt icon-black"></i>
                      <% end %> |
                      <%= link_to personal_assign_shift_path(employee) do %>
                          <i class="icon-tag icon-black"></i>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
            </table>
            <%= render 'legend_list' %>
            <%= will_paginate @employees, renderer: BootstrapPagination::Rails %>
        <% end %>
    </div>
</div>